var fakeReviewData = [
  {
    "id": 1,
    "comment": "This guy was incredible. I really can't tell you how much you should hire him. If youre not paying the geyser upward of 100 big ones, id be suprised. Love I love Darth Vadar",
    "rating": 4,
    "ReviewFrom": 1,
    "ReviewFor": 2,
    "createdAt": "2016-11-18T23:37:13.533Z",
    "updatedAt": "2016-11-18T23:37:13.533Z",
    "reviewerName": "Sarah Harris",
    "reviewerImage": "http://robertrosenthal.typepad.com/photos/uncategorized/ist_2.jpg",
  },
  {
    "id": 2,
    "comment": "This guy was incredible. I really can't tell you how much you should hire him. If youre not paying the geyser upward of 100 big ones, id be suprised. Love I love Yoda",
    "rating": 4,
    "ReviewFrom": 1,
    "ReviewFor": 2,
    "createdAt": "2016-11-18T23:37:15.241Z",
    "updatedAt": "2016-11-18T23:37:15.241Z",
    "reviewerName": "Mary Dickens",
    "reviewerImage": "https://s-media-cache-ak0.pinimg.com/originals/94/e1/3d/94e13da37c0ff69bc85481418516b5fd.jpg",
  },
  {
    "id": 3,
    "comment": "This guy was incredible. I really can't tell you how much you should hire him. If youre not paying the geyser upward of 100 big ones, id be suprised. Love Bananas",
    "rating": 4,
    "ReviewFrom": 1,
    "ReviewFor": 2,
    "createdAt": "2016-11-18T23:37:26.032Z",
    "updatedAt": "2016-11-18T23:37:26.032Z",
    "reviewerName": "Carlos Millidge",
    "reviewerImage": "http://speakingaboutpresenting.com/wp-content/uploads/2009/01/istock_businessman.jpg",
  },
  {
    "id": 5,
    "comment": "This guy was incredible. I really can't tell you how much you should hire him. If youre not paying the geyser upward of 100 big ones, id be suprised. Love Marcus",
    "rating": 4,
    "ReviewFrom": 1,
    "ReviewFor": 2,
    "createdAt": "2016-11-18T23:37:50.044Z",
    "updatedAt": "2016-11-18T23:37:50.044Z",
    "reviewerName": "Boyd Mcgee",
    "reviewerImage": "http://speakingaboutpresenting.com/wp-content/uploads/2009/01/younger-business-woman.jpg",
  },
  {
    "id": 6,
    "comment": "This guy was incredible. I really can't tell you how much you should hire him. If youre not paying the geyser upward of 100 big ones, id be suprised. Love Fred",
    "rating": 4,
    "ReviewFrom": 1,
    "ReviewFor": 2,
    "createdAt": "2016-11-18T23:37:53.578Z",
    "updatedAt": "2016-11-18T23:37:53.578Z",
    "reviewerName": "Guy Linton",
    "reviewerImage": "https://www.alvinailey.org/sites/default/files/styles/slideshow_image/public/melanie-person.jpg?itok=ocw3xkx_",
  }
]

export default fakeReviewData;