const fakeJobData = [
  {
    id: 1,
    title: 'Shower Remodel',
    hires: '4',
    location: 'San Francisco',
    pay: '$32 /hour',
    ownerName: 'John Anderson',
    ownerImage: 'http://www.solotradie.com/wp-content/uploads/2015/04/tradesman_laptop.jpg',
    description: 'This is a description of the job. It should be about this long. Hopefully it is informative but short.',
    expertise: 'plumber',
    time: 'Mar 23 - Mar 29',
    mobile: '0432211241',
  },
  {
    id: 2,
    title: 'Bathroom Fitting',
    hires: '2',
    location: 'Oakland',
    pay: '$24 /hour',
    ownerName: 'Steve Smith',
    ownerImage: 'http://www.publicliability.co/wp-content/uploads/2012/07/public-liability-insurance-for-tradesmen.jpg',
    description: 'This is a description of the job. It should be about this long. Hopefully it is informative but short.',
    expertise: 'plumber',
    time: 'Mar 23 - Mar 29',
    mobile: '0432211241',
  },
  {
    id: 3,
    title: 'Toilet Repair',
    hires: '3',
    location: 'Mountain View',
    pay: '$28 /hour',
    ownerName: 'Bob Jones',
    ownerImage: 'http://landscaping-kwikfynd.com.au/pictures/product-images/landscaping/landscape-tradesman/landscape-tradesman-14.jpg',
    description: 'This is a description of the job. It should be about this long. Hopefully it is informative but short.',
    expertise: 'plumber',
    time: 'Mar 23 - Mar 29',
    mobile: '0432211241',
  },
];

export default fakeJobData;
